<?php
namespace App;

class PrivilegiosConstants
{
    /* PRESUPUESTO */
    const PRESUPUESTO_CONSULTA_TODOS_LOS_DEPARTAMENTOS=1;
    const PRESUPUESTO_APROBACION_PRESUPUESTOS=2;
    const PRESUPUESTO_INGRESAR_PRESUPUESTO=3;
    const PRESUPUESTO_CONSULTA_CONTADOR_DEPARTAMENTO=4;
    /*PLANIFICACION*/
    const PLANIFIACION_INGRESAR_PLANIFICACION=100;
}