<?php
namespace App;

class PrivilegiosConstants
{
    /* PRESUPUESTO */
    const PRESUPUESTO_CONSULTA_TODOS_LOS_DEPARTAMENTOS=1;
    const PRESUPUESTO_APROBACION_PRESUPUESTOS=2;
    const PRESUPUESTO_INGRESAR_PRESUPUESTO=3;
    const PRESUPUESTO_CONSULTA_CONTADOR_DEPARTAMENTO=4;
    /*PLANIFICACION*/
    const PLANIFIACION_INGRESAR_PLANIFICACION=100;
    const PLANIFICACION_CONSULTA_REGIONES=101;
    const PLANIFICACION_CREAR_PROYECTO=102;
    const PLANIFICACION_APROBAR_PLANIFICACION=103;
      
    /* MONITOREO */
    const MONITEO_ADMINISTRACION=200;
    
    /* REPORTES */

    /* CONFIGURACION */
    const CONFIGURACION_ACCESO=400;
    
    /* SEGURIDAD */
    const SEGURIDAD_ACCESO=500;
}