<?php
namespace App;

class PrivilegiosConstants
{
    const PRESUPUESTO_CONSULTA_TODOS_LOS_DEPARTAMENTOS=1;
    const PRESUPUESTO_APROBACION_PRESUPUESTOS=2;
    const PRESUPUESTO_INGRESAR_PRESUPUESTO=3;
    
}